server:
  port: 8080
spring:
  application:
    name: AUTH-APP
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/emp_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
security:
  jwt:
    secret-key : 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000
